FROM denoland/deno:2.5.2

WORKDIR /app/httpapi

# Environment variables with defaults
ENV HTTP_PORT=8000
ENV HTTP_HOSTNAME=0.0.0.0

EXPOSE 8000

# The actual code will be mounted as volumes
CMD ["deno", "run", "--allow-net", "--allow-read", "--allow-write", "--allow-env", "--unstable-kv", "--watch", "/app/httpapi/src/server.ts"]
