FROM denoland/deno:2.5.2

WORKDIR /app/wsserver

# Environment variables with defaults
ENV WS_PORT=8001
ENV WS_HOSTNAME=0.0.0.0

EXPOSE 8001

# The actual code will be mounted as volumes
CMD ["deno", "run", "--allow-net", "--allow-read", "--allow-write", "--allow-env", "--watch", "/app/wsserver/main.ts"]
