------------------------- MODULE MCTemporalConsensus ---------------------------
(****************************************************************************)
(* Model Checking Configuration for TemporalConsensus                       *)
(*                                                                          *)
(* This module instantiates the TemporalConsensus specification with        *)
(* concrete values suitable for TLC model checking.                         *)
(*                                                                          *)
(* Multiple configurations are defined; uncomment the desired one.          *)
(****************************************************************************)

EXTENDS TemporalConsensus

(****************************************************************************)
(* CONFIGURATION 1: Minimal — N=3, K=3, f=0                                *)
(* No Byzantine validators. Verifies basic protocol correctness.            *)
(* State space: small, completes in seconds.                                *)
(*                                                                          *)
(* TLC command:                                                             *)
(*   java -jar tla2tools.jar -config MC1.cfg MCTemporalConsensus            *)
(*                                                                          *)
(* MC1.cfg contents:                                                        *)
(*   CONSTANTS                                                              *)
(*     N = 3                                                                *)
(*     K = 3                                                                *)
(*     f = 0                                                                *)
(*     MaxSlot = 3                                                          *)
(*     F = 2                                                                *)
(*     Validators = {v1, v2, v3}                                            *)
(*     Messages = {m1, m2}                                                  *)
(*     Byzantine = {}                                                       *)
(*   INVARIANT Safety                                                       *)
(*   INVARIANT TypeOK                                                       *)
(*   PROPERTY LivenessProgress                                              *)
(****************************************************************************)

(****************************************************************************)
(* CONFIGURATION 2: N=3, K=3, f=1 (one Byzantine)                          *)
(* Tests safety with minority Byzantine. T=2, so 1 Byzantine < T.          *)
(* Safety should hold. Liveness should hold.                                *)
(*                                                                          *)
(* MC2.cfg contents:                                                        *)
(*   CONSTANTS                                                              *)
(*     N = 3                                                                *)
(*     K = 3                                                                *)
(*     f = 1                                                                *)
(*     MaxSlot = 3                                                          *)
(*     F = 2                                                                *)
(*     Validators = {v1, v2, v3}                                            *)
(*     Messages = {m1, m2}                                                  *)
(*     Byzantine = {v3}                                                     *)
(*   INVARIANT Safety                                                       *)
(*   INVARIANT TypeOK                                                       *)
(****************************************************************************)

(****************************************************************************)
(* CONFIGURATION 3: N=3, K=3, f=2 (two Byzantine — safety violation!)      *)
(* T=2, f=2, so f >= T. Byzantine can confirm conflicting messages.         *)
(* Safety SHOULD FAIL — this is a negative test.                            *)
(*                                                                          *)
(* MC3.cfg contents:                                                        *)
(*   CONSTANTS                                                              *)
(*     N = 3                                                                *)
(*     K = 3                                                                *)
(*     f = 2                                                                *)
(*     MaxSlot = 2                                                          *)
(*     F = 1                                                                *)
(*     Validators = {v1, v2, v3}                                            *)
(*     Messages = {m1, m2}                                                  *)
(*     Byzantine = {v2, v3}                                                 *)
(*   INVARIANT Safety                                                       *)
(*   INVARIANT TypeOK                                                       *)
(****************************************************************************)

(****************************************************************************)
(* CONFIGURATION 4: N=5, K=3, f=1                                          *)
(* Larger validator set, small committee. Tests committee sampling.         *)
(*                                                                          *)
(* MC4.cfg contents:                                                        *)
(*   CONSTANTS                                                              *)
(*     N = 5                                                                *)
(*     K = 3                                                                *)
(*     f = 1                                                                *)
(*     MaxSlot = 3                                                          *)
(*     F = 2                                                                *)
(*     Validators = {v1, v2, v3, v4, v5}                                    *)
(*     Messages = {m1, m2}                                                  *)
(*     Byzantine = {v5}                                                     *)
(*   INVARIANT Safety                                                       *)
(*   INVARIANT TypeOK                                                       *)
(****************************************************************************)

(****************************************************************************)
(* CONFIGURATION 5: N=5, K=5, f=2                                          *)
(* Full committee. T=3. f=2 < T=3, so safety should hold.                  *)
(* But liveness depends on committee composition.                           *)
(*                                                                          *)
(* MC5.cfg contents:                                                        *)
(*   CONSTANTS                                                              *)
(*     N = 5                                                                *)
(*     K = 5                                                                *)
(*     f = 2                                                                *)
(*     MaxSlot = 2                                                          *)
(*     F = 1                                                                *)
(*     Validators = {v1, v2, v3, v4, v5}                                    *)
(*     Messages = {m1, m2}                                                  *)
(*     Byzantine = {v4, v5}                                                 *)
(*   INVARIANT Safety                                                       *)
(*   INVARIANT TypeOK                                                       *)
(****************************************************************************)

(****************************************************************************)
(* CONFIGURATION 6: N=7, K=5, f=2                                          *)
(* Recommended production-like config (from E2). T=3, f=2 < T.             *)
(* Safety should hold. Liveness may fail if committee gets 3+ Byzantine.    *)
(* With N=7, f=2, K=5: possible to draw committee with 2 Byzantine.        *)
(* Since 2 < 3 = T, safety holds even in worst-case committee.             *)
(*                                                                          *)
(* MC6.cfg contents:                                                        *)
(*   CONSTANTS                                                              *)
(*     N = 7                                                                *)
(*     K = 5                                                                *)
(*     f = 2                                                                *)
(*     MaxSlot = 2                                                          *)
(*     F = 1                                                                *)
(*     Validators = {v1, v2, v3, v4, v5, v6, v7}                            *)
(*     Messages = {m1, m2}                                                  *)
(*     Byzantine = {v6, v7}                                                 *)
(*   INVARIANT Safety                                                       *)
(*   INVARIANT TypeOK                                                       *)
(****************************************************************************)

(****************************************************************************)
(* SYMMETRY SETS                                                            *)
(*                                                                          *)
(* For efficient model checking, declare symmetry on Messages.              *)
(* Validators should NOT be symmetric because Byzantine breaks symmetry.    *)
(*                                                                          *)
(* In the .cfg file, add:                                                   *)
(*   SYMMETRY MessageSymmetry                                               *)
(****************************************************************************)

\* Symmetry set for messages — all messages are interchangeable
\* (they have no inherent meaning, only identity matters)
MessageSymmetry == Permutations(Messages)

(****************************************************************************)
(* STATE CONSTRAINT                                                         *)
(*                                                                          *)
(* Bound the state space to make model checking feasible.                   *)
(* In the .cfg file, add:                                                   *)
(*   CONSTRAINT StateConstraint                                             *)
(****************************************************************************)

StateConstraint == currentSlot <= MaxSlot

(****************************************************************************)
(* ACTION CONSTRAINT                                                        *)
(*                                                                          *)
(* Limit Byzantine behavior to reduce state space if needed.                *)
(* Byzantine validators can attest to at most 2 messages per slot.          *)
(****************************************************************************)

ByzAttestationBound ==
    \A s \in 1..MaxSlot :
        \A v \in Byzantine :
            Cardinality({m \in Messages : <<v, m>> \in attestations[s]}) <= 2

(****************************************************************************)
(* CONFIGURATION TEMPLATES                                                  *)
(*                                                                          *)
(* Example .cfg file for TLC (MC1.cfg):                                     *)
(*                                                                          *)
(* SPECIFICATION Spec                                                       *)
(*                                                                          *)
(* CONSTANTS                                                                *)
(*   N = 3                                                                  *)
(*   K = 3                                                                  *)
(*   f = 0                                                                  *)
(*   MaxSlot = 3                                                            *)
(*   F = 2                                                                  *)
(*   v1 = v1                                                                *)
(*   v2 = v2                                                                *)
(*   v3 = v3                                                                *)
(*   m1 = m1                                                                *)
(*   m2 = m2                                                                *)
(*   Validators = {v1, v2, v3}                                              *)
(*   Messages = {m1, m2}                                                    *)
(*   Byzantine = {}                                                         *)
(*                                                                          *)
(* SYMMETRY MessageSymmetry                                                 *)
(* CONSTRAINT StateConstraint                                               *)
(*                                                                          *)
(* INVARIANT TypeOK                                                         *)
(* INVARIANT Safety                                                         *)
(* PROPERTY LivenessProgress                                                *)
(*                                                                          *)
(****************************************************************************)

(****************************************************************************)
(* SUMMARY OF CONFIGURATIONS AND EXPECTED RESULTS                           *)
(*                                                                          *)
(*  Config | N | K | f | T | Safety? | Liveness? | Notes                    *)
(*  -------+---+---+---+---+---------+-----------+--------------------      *)
(*  MC1    | 3 | 3 | 0 | 2 | PASS    | PASS      | No adversary            *)
(*  MC2    | 3 | 3 | 1 | 2 | PASS    | PASS      | f < T                   *)
(*  MC3    | 3 | 3 | 2 | 2 | FAIL    | FAIL      | f >= T (counterex)      *)
(*  MC4    | 5 | 3 | 1 | 2 | PASS*   | PASS      | *if comm has <= 1 byz   *)
(*  MC5    | 5 | 5 | 2 | 3 | PASS    | PASS      | f < T, full committee   *)
(*  MC6    | 7 | 5 | 2 | 3 | PASS    | PASS      | E2-recommended config   *)
(*                                                                          *)
(* MC4 note: With N=5, K=3, f=1, the committee may or may not contain      *)
(* the Byzantine validator. Safety holds because even if the Byzantine      *)
(* validator is on the committee, 1 < T=2, so it cannot single-handedly    *)
(* confirm a conflicting message. The honest majority (2 of 3) always      *)
(* agrees on the proposed message.                                          *)
(****************************************************************************)

=============================================================================
